### PR TITLE
added raj-hero as contributer

### PR DESCRIPTION
**Pull request by raj-hero**
Do add the hacktoberfest-accepted tag if no issues are found. Do highlight if any issues are found.

### CODE REVIEW

**Review by spykelionel — CHANGES_REQUESTED** [review]
Only a single file should change for this pull request

**Comment by raj-hero** [comment]
@Fienne and @spykelionel Has this repo been excluded from hacktoberfest2022?

**Comment by spykelionel** [comment]
> @Fienne and @spykelionel Has this repo been excluded from hacktoberfest2022?

It has been merged @raj-hero

**Comment by yokwejuste** [comment]
> @Fienne and @spykelionel Has this repo been excluded from hacktoberfest2022?

The repo is valid and still on gong so chill Mehn

**Comment by raj-hero** [comment]
> > @Fienne and @spykelionel Has this repo been excluded from hacktoberfest2022?
> 
> The repo is valid and still on gong so chill buddy

But my Hacktoberfest account says something weired.
Screen Shot 2022-10-02 at 8 07 58 AM

**Comment by raj-hero** [comment]
> > > @Fienne and @spykelionel Has this repo been excluded from hacktoberfest2022?
> > 
> > 
> > The repo is valid and still on gong so chill buddy
> 
> But my Hacktoberfest account says something weired. Screen Shot 2022-10-02 at 8 07 58 AM

@Fienne and @spykelionel do guide me what is to be done to resolve this issue. Moreover, how to make this a valid PR for hacktoberfest?

**Pull request merged**
