### PR TITLE
feat: added MR-DHRUV as contributor

### PR DESCRIPTION
**Pull request by MR-DHRUV**

### CODE REVIEW

**Comment by MR-DHRUV** [comment]
@DSCUBa2020 as there were errors of double quotes and  "," in the JSON , I fixed them and that's the reason for merge conflicts

**Comment by yokwejuste** [comment]
image

**Comment by MR-DHRUV** [comment]
@Burnleydev1 Sure and Thanks :-)

**Comment by yokwejuste** [comment]
> image

as you can see here @MR-DHRUV there are some item is removing from our file. please can you have a look at that?

**Comment by MR-DHRUV** [comment]
@yokwejuste sure, I'm looking into it.

**Comment by Burnleydev1** [comment]
Hi @MR-DHRUV It seems you never fetched for the current changes in master before creating your pr, so the most recent changes  are excluded from your pr, Can you kindly add them back?

**Comment by Burnleydev1** [comment]
Hi @MR-DHRUV , It seems you have not added your information here.

**Comment by Burnleydev1** [comment]
I think it's all good now @MR-DHRUV , Thanks for helping out

**Comment by MR-DHRUV** [comment]
@Burnleydev1 You are utmost welcome

**Pull request merged**
