### PR TITLE
Adding my username Aravindhsiva as Contributor

### PR DESCRIPTION
**Pull request by Aravindhsiva**

### CODE REVIEW

**Comment by Burnleydev1** [comment]
Hello @yokwejuste I kept getting This page is out of date. [Start over](https://github.com/Developer-Student-Clubs-UBa/hactoberfest2022/pull/69/conflicts) when I merge the solved conflict into [Aravindhsiva:patch-1](https://github.com/Aravindhsiva/hactoberfest2022/tree/patch-1)

**Comment by yokwejuste** [comment]
> Hello @yokwejuste I kept getting This page is out of date. [Start over](https://github.com/Developer-Student-Clubs-UBa/hactoberfest2022/pull/69/conflicts) when I merge the solved conflict into [Aravindhsiva:patch-1](https://github.com/Aravindhsiva/hactoberfest2022/tree/patch-1)

Let me try solving it

**Comment by Fienne** [comment]
> > Hello @yokwejuste I kept getting This page is out of date. [Start over](https://github.com/Developer-Student-Clubs-UBa/hactoberfest2022/pull/69/conflicts) when I merge the solved conflict into [Aravindhsiva:patch-1](https://github.com/Aravindhsiva/hactoberfest2022/tree/patch-1)
> 
> Let me try solving it

I guess I fixed it.. I don't know if the hacktober_fest round value is correct though because the info was mixed up

**Review by yokwejuste — COMMENTED** [review]
all good with the code base!

**Comment by Burnleydev1** [comment]
@Fienne, I thought it was about if this was their first second or third round, Thanks for the fix.

**Comment by Aravindhsiva** [comment]
Oops, missed the hacktoberfest-accepted label !!

**Comment by Burnleydev1** [comment]
@Aravindhsiva No it is all good the label is to be added by a maintainer, I guess you're good here.

**Pull request merged**
