### PR TITLE
update task 1,2,3

### PR DESCRIPTION
**Pull request by NishaChawla18**

### CODE REVIEW

**Comment by Burnleydev1** [comment]
Hello @NishaChawla18 , you have to create a new branch for each pull request that is solving a specific task
For example task 1 should be from abranch called task-1 same for task 2 3 and 4.

**Comment by Burnleydev1** [comment]
Be sure to create a branch for each task please.

**Comment by NishaChawla18** [comment]
ok i will check

**Comment by Burnleydev1** [comment]
please you will begin from task 1 once more

**Comment by Burnleydev1** [comment]
to avoid conflicts

**Comment by NishaChawla18** [comment]
ok 
I created for other tasks can you please validate

**Pull request closed without merging**
