### PR TITLE
feat: added my techstack - hrishikesh-g

### PR DESCRIPTION
**Pull request by hrishikesh-g**
feat: added my techstack - hrishikesh-g

### CODE REVIEW

**Review by spykelionel — CHANGES_REQUESTED** [review]
Update a single file at a time. So many changes.
Please revert and create a new PR

**Comment by hrishikesh-g** [comment]
Hello sir, I am new to github, and did as per whatever was asked to do.  I am not able to understand this issue sir. 
can you please explain what can I do to solve this issue?

**Comment by spykelionel** [comment]
Ok. Go through, [the contribution rules](https://github.com/Developer-Student-Clubs-UBa/hactoberfest2022/blob/master/Task1/README.md#contribution)

**Comment by hrishikesh-g** [comment]
sir I did as asked but I don't know how the previous commits are also getting added in this commit. And what do I do to solve this issue.

**Comment by spykelionel** [comment]
Delete your branch. OR your repo. Fork this repo again, and do the contribution
When checking out to a new branch, use `git checkout -b <your-task-name> master`

**Comment by hrishikesh-g** [comment]
Thank you so much for your help. I will create a new fork. But how do I prevent the previous commits of the tasks from being included while pushing a commit for eg. task4. 
In this push for task4, the commits from task2 ,task3 also got included.

**Comment by spykelionel** [comment]
Only necessary commits will be included. Thanks for understanding

**Pull request closed without merging**
